file = {"sched.lua", "mutex.lua", "catalog.lua", "pipes.lua"
	, "tasks/nixiorator.lua", "tasks/socketeer.lua"}
project = "Lumen"
description = "A cooperative scheduler for Lua tasks"
format = 'markdown'
examples={'tests/test.lua', 'tests/test-buff.lua', 'tests/test-nixiorator.lua'
	, 'tests/test-socketeer.lua', 'tests/test-pipe.lua', 'tests/test-stress.lua'
	, 'tests/test-multiwait.lua'}
readme = "README.md"

